version: '3.8'

services:
  auth:
    image: pramod003/car-price-ms:1.0.0-auth
    hostname: auth
    container_name: auth
    restart: always
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 215M
        reservations:
          cpus: '0.25'
          memory: 215M
    networks:
      - carprice-predictor

  predict:
    image: pramod003/car-price-ms:1.0.0-predict
    hostname: predict
    container_name: predict
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 215M
        reservations:
          cpus: '0.25'
          memory: 215M
    networks:
      - carprice-predictor

  model:
    image: pramod003/car-price-ms:1.0.0-models
    hostname: model
    container_name: model
    restart: always
    ports:
      - "8001:8001"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 215M
        reservations:
          cpus: '0.25'
          memory: 215M
    networks:
      - carprice-predictor
    depends_on:
     - auth

networks:
  carprice-predictor:
    driver: bridge

