apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: external-secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.4
    helm:
      values: |         
        replicaCount: 1
        fullnameOverride: "external-secrets"
        clusterName: microservice-bike
        clusterEndpoint: ${dependency.eks.outputs.cluster_endpoint}
        serviceAccount:
         name: external-secrets-operator
         annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::767398056657:role/ms-stag-microservice-bike-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false