apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: models
  namespace: ms
  annotations:
    cert-manager.io/cluster-issuer: letsecrypt-prod
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  ingressClassName: external-nginx
  tls: 
    - secretName: predict-api-tls
      hosts:
        - predict-api.slicearrow.com
  rules:
    - host: "predict-api.slicearrow.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: models
                port:
                  number: 8001
