apiVersion: v1
kind: ResourceQuota
metadata:
  name: microservice
  namespace: ms
spec:
  hard:
    requests.cpu: "10"
    limits.cpu: "10"
    limits.memory: "5Gi"
    persistentvolumeclaims: "5"
    pods: "100"
    services: "5"
    secrets: "30"
    configmaps: "10"
    replicationcontrollers: "20"
    resourcequotas: "1"
    requests.storage: "10Gi"
    services.loadbalancers: "1"
