apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-quota
  namespace: example-namespace
spec:
  hard:
    requests.cpu: "20"
    limits.cpu: "40"
    limits.memory: "128Gi"
    persistentvolumeclaims: "10"
    pods: "50"
    services: "5"
    secrets: "20"
    configmaps: "10"
    replicationcontrollers: "10"
    resourcequotas: "1"
    requests.storage: "500Gi"
    services.loadbalancers: "2"
