apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-.env: "kv/projects/bike-price-prediction"
        vault.hashicorp.com/agent-inject-template-.env: |
          {{- with secret "kv/projects/bike-price-prediction" -}}
            {{ .Data.data.auth }}
          {{- end }}
        vault.hashicorp.com/secret-volume-path: /vault/secrets
        vault.hashicorp.com/agent-inject-file-.env: /.env  # Change the path to root
        vault.hashicorp.com/log-level: "debug"
        vault.hashicorp.com/role: "test"
    spec:
      serviceAccountName: auth
      containers:
        - name: auth
          image: pramod003/car-price-ms:1.0.1-auth
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 3
            failureThreshold: 6
            periodSeconds: 9
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 3
            failureThreshold: 9
            periodSeconds: 6
          startupProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 3
            failureThreshold: 6
            periodSeconds: 9
