apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: ms
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      securityContext:
        runAsUser: 1000
      serviceAccountName: auth
      containers:
        - name: auth
          image: pramod003/car-price-ms:4.0.0-auth
          ports:
            - containerPort: 8000
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - CAP_NET_BIND_SERVICE
                - CAP_SYS_TIME
                - CAP_DAC_OVERRIDE
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8000
          #   initialDelaySeconds: 3
          #   failureThreshold: 6
          #   periodSeconds: 9
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8000
          #   initialDelaySeconds: 3
          #   failureThreshold: 9
          #   periodSeconds: 6
          # startupProbe:
          #   httpGet:
          #     path: /
          #     port: 8000
          #   initialDelaySeconds: 3
          #   failureThreshold: 6
          #   periodSeconds: 9
