name: Build docker image

on:
  push:
    branches:
      - auth

jobs:
  build:
    uses: pramodh003/car-price-prediction-ms/.github/workflows/main.yml@main
    with:
      branch_name: ${{ github.ref_name }}
    secrets: inherit
