apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: ms
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-.env: "kv/projects/bike-price-prediction"
    vault.hashicorp.com/role: "test"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/agent-inject-template-.env: |
      {{ with secret "kv/projects/bike-price-prediction" -}}
        {{ .Data.data.auth }}
      {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      securityContext:
        runAsUser: 1000
      serviceAccountName: auth
      containers:
        - name: auth
          image: pramod003/car-price-ms:1.0.1-auth
          ports:
            - name: http
              containerPort: 8000
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - CAP_NET_BIND_SERVICE
                - CAP_SYS_TIME
                - CAP_DAC_OVERRIDE
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 3
            failureThreshold: 6
            periodSeconds: 9
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 3
            failureThreshold: 9
            periodSeconds: 6
          startupProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 3
            failureThreshold: 6
            periodSeconds: 9
